Before commit.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -17,26 +17,32 @@ env:
   global:
     - CWD="$TRAVIS_BUILD_DIR"
     - GIT_TRACE=0
-    - DISPLAY=:0.0 DISPLAY_BACKUP=$DISPLAY WINEDLLOVERRIDES="mscoree,mshtml=" WINEDEBUG="fixme+all"
     - UPSTREAM_USER='d-a-t-a-d-i-t'
     - USER=${TRAVIS_REPO_SLUG%%/*}
     - REPOSITORY=${TRAVIS_REPO_SLUG##*/}
+    - DISPLAY=:0.0 DISPLAY_BACKUP=$DISPLAY WINEDLLOVERRIDES="mscoree,mshtml=" WINEDEBUG="fixme+all"
     - PATH=${PATH//:\.\/node_modules\/\.bin/} # Fixes Travis bug: https://github.com/travis-ci/travis-ci/issues/4862
     - secure: "crXsd5puGxZaDE9EVTDLU0tMeH3JRmIAUwLhBjheBPzbzT/buE1owFsaeGsr/XQStNrt2EWq8LxN/c4TOkHJ9tTU8f6+3IUkAXvzqYwwcE+HbY3KJ4jJd2KHRQ5NbwpAkDtADvcrw5CDdWGmMiOEaA54l4GCBg0Id5jWOy2KbKXBnjWeaZu6irYT1B6HMAYSxPKWVHriku323tgH3FgAn1HtKK2nhOPjulBj6vj/ioS7xy20sz9j2yN7hExGB1k0GGUSNi7O74xYqLHhBJISp7LplHbaTJCMi5/xd9h9kSfsTLxJtXTqxat/92JburhzFvGBEjd4gJOiZxJw0vymTVJaqwpfy7joD3QD6jz/nF7w5HSnTvEly6wLCOH00TbrfPvwPvFvfXTFl6diNZEfZCwiSJa9eM88hDkpPyp8+O2w9TprASI66qmsM2z3vt2UM4L5k5QfYrIVPE9J4LE1btjX4cecQVb1oauE5N9Hr77e92R5lfA7LgAcT5TluG5AMNJSEbDmdYrnz9W+nlm+2ML3OhdfWHvcvMFSI0Cjpn+9ZF88pGFBc0qjiQQPJCq7WwBgC3pMYsuioV92BNevCDtzCEPL4hp/oc69K+tKxzb4/OdFWSJO5zEKOno1FCheFHLTNl7qbDUt/5xz08hSwtWf7aR5da1CT7eG4RVJCoY="
     - secure: "eMGIXPSYLk1LIxqocS3CuHl+vxUSr1ZDs38yNdA6jwc/7zeWn7zA0+N2zHKr9UzkHDYJ9cbLDlJZk/M8umtDr3H3orld3TCSXMgtyKqCdDV3T4rwmcJs3InyrOa7Ia72FNJttjpToQ53oWnMqCk/eN7sLL4ZJLmJxAlkW5JK5fml0UYn03jrE3ggXmjjm/CpjrkurgfioDL7xhxtnACHCNuWRupXxI4486rzAW6enqrluVcr25a0Zn7ZAAseIxqQhEuUqiyJlKRcrlaO3yDYIa1AI0drLYMlmOcEAxcSzVIwTX79CV4C7UQWg2SHYOXYK+ak+AXwKvr8Q4y5u4PZBvBZTOELHRW61MvDq5NjAvvEgc5VvHtsWG7b0Qqe0N3EU4cJBqLfeOettFd4rA+VBRgUVoUXaXgQlKibKBG4kBEM030mIfLzTMAAYduYNiallzffGhn4ZRzTQPOAM298sh5moIo5yIl+1z2bxEXXz0BOs273JZNhBBXzS1CSQoeHZEVvETnnWAUvnNPrZ6moQ6/gkabhyV1jUNiplxGoJ9bSShPzwh1rfgskAyHBrvGiNLnRzU5bx0YJRqT7njqRhPCXfVEa7Q5qWtrXwWF/DNDd9gbeocedsHAsmzlLgfeJsJiVX+9jM7w0/NlHowjhPnBZJYq2dLSzzku6/5Vv/WA="
   matrix:
     - PLATFORM=MT4 MODE=Lite
 
+notifications:
+  email: true
+  webhooks:
+    #urls: https://webhooks.gitter.im/e/2c50114866dd0ba72f48
+    on_success: change  # options: [always|never|change] default: always
+    on_failure: always  # options: [always|never|change] default: always
+    on_start:   never   # options: [always|never|change] default: always
+
+
 # Before Install
 # Use this to prepare the system to install prerequisites or dependencies.
 # Commonly used to update git repository submodules and do similar tasks that need to be performed before dependencies are installed.
 before_install:
-  - echo "UPSTREAM_USER=$UPSTREAM_USER"
-  - echo "USER=$USER"
-  - echo "REPOSITORY=$REPOSITORY"
-  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
+  - env
   - |
-    # Send pull-request to upstream repository if Travis is running in a forked repository
+    # Send pull request to upstream repository if Travis is running in a forked repository
     if [ "$USER" != "$UPSTREAM_USER" ]; then
       # Check if the forker's GitHub access token was passed to Travis
       if [ -z "$OAUTH_TOKEN" ]; then
@@ -44,27 +50,25 @@ before_install:
         exit 1
       fi
 
-      # Send pull-request to upstream (main) repository for doing the backtests
-      CURL_STATUS=$(curl -siH "Authorization: token $OAUTH_TOKEN" -d '{"title": "'"$(date --rfc-3339=seconds) [ci skip]"'", "base": "'$TRAVIS_BRANCH'", "head": "'$USER':'$TRAVIS_BRANCH'"}' https://api.github.com/repos/$UPSTREAM_USER/$REPOSITORY/pulls | head -n1 | cut -d' ' -f2) #'
-      echo "CURL_STATUS=$CURL_STATUS"
-      if [ "$CURL_STATUS" != "201" ]; then
-        exit 1  # TODO Provide some useful message...
+      # Send pull request to upstream (main) repository for doing the backtests
+      PR_HTTP_STATUS=$(curl -siH "Authorization: token $OAUTH_TOKEN" -d '{"title": "PR to backtest", "base": "'$TRAVIS_BRANCH'", "head": "'$USER':'$TRAVIS_BRANCH'"}' https://api.github.com/repos/$UPSTREAM_USER/$REPOSITORY/pulls | head -n1 | cut -d' ' -f2)
+      if [ "$PR_HTTP_STATUS" != "201" ]; then
+        echo "[ERROR] Unable to create new pull request, please check if your access token is valid and you haven't had already an open pull request!"
+        echo "PR_HTTP_STATUS=$PR_HTTP_STATUS"
+        exit 1
       fi
       exit 0
     else
+      # If pull request was sent to upstream repository (via Travis or manually) notify the sender about it, ...
       if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
-        echo "[WARNING] This build ran in the upstream repo, but only on the virtual branch of the pull request!"
-        echo "          Please wait until the owner of uptream repository merges your changes."
+        echo "[INFO] Your changes are staged in the upstream repository, please wait until they are merged for running the backtests."
         exit 0
       fi
     fi
 
-  - echo '[OK] Building on upstream:master.'
-
-  # || WTF4
   # ||
+  # ||  ... otherwise continue with preparing and doing the backtests on master branch of the upstream repository
   # \/
-  - env
 
   # Add PPA/Wine repository
   - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
@@ -116,21 +120,21 @@ script:
       ln -s "$EA_SAMPLE" "/vagrant/$MODE.ex4"
     fi
   - $CWD/_VM/scripts/dl_bt_data.sh
+  # Run backtests in a new branch and push results back to upstream repository
   - NEW_BRANCH="EA-$(date +%Y%m%d)"
-  - echo "NEW_BRANCH=$NEW_BRANCH"
   - git checkout -b $NEW_BRANCH
-  - $CWD/_scripts/run_backtests.sh "$MODE"
-  - git add -vA "$MODE"
+  - $CWD/_scripts/run_backtests.sh $MODE
+  - find $MODE -type f -regex '.*Report\.\(htm\|gif\)' -delete  # Workaround for FX-MT-VM/scripts/run_backtest.sh:34
+  - git add -vA $MODE
   - git config user.name $USER
   - git config user.email $USER'@users.noreply.github.com'
-  - git commit -am 'New commit. [ci skip]'
+  - git commit -am 'Reports of branch $NEW_BRANCH. [ci skip]'
   - |
     # Check if the GitHub access token of main repository was passed to Travis
     if [ -z "$OAUTH_TOKEN" ]; then
       echo "Please set the OAUTH_TOKEN environment variable in Travis CI with a valid access token which has the 'public_repo' scope."
       exit 1
     fi
-  - git remote -v  # REMOVE_ME
   - git push --set-upstream https://$UPSTREAM_USER:$OAUTH_TOKEN@github.com/$UPSTREAM_USER/$REPOSITORY $NEW_BRANCH
 
 
